name: Publish Documentation

on:
  workflow_dispatch:

env:
  WYAM_ACCESS_TOKEN: ${{ secrets.API_TOKEN }}
  # secrets.GITHUB_TOKEN has no permissions to push, sadly.
  WYAM_DEPLOY_BRANCH: 'gh-pages'
  WYAM_DEPLOY_REMOTE: "${{ github.event.repository.html_url }}"

jobs:
  cake:
    runs-on: ubuntu-22.04

    steps:
    - name: checkout
      uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4

    - name: Fetch all tags and branches
      run: git fetch --prune --unshallow

    - name: Cache Tools
      uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # v4
      with:
        path: tools
        key: ${{ runner.os }}-doc-tools-${{ hashFiles('recipe.cake') }}

    - name: Publishing documentation
      uses: cake-build/cake-action@v2
      with:
        script-path: recipe.cake
        target: Force-Publish-Documentation
        verbosity: Diagnostic
        cake-version: 1.3.0